### ISSUE TITLE
Create phone app as device (Android)

### ISSUE THREAD

**Issue by spyrossak** [Azure/connectthedots#114]
same as Windows Phone item, but for Android

**Comment by varunagrawal** [comment]
Can Xamarin be used to get this done quickly? Or do you require a native android app?

**Comment by lt72** [comment]
I think Xamarin is not needed, but I'll need to check the feature set of Windows Phone up more closely first. I plan to engage next week or slightly after

**Comment by olivierbloch** [comment]
We now have a Xamarin sample
