### ISSUE TITLE
Add Device Operations Using Downlink messages

### ISSUE THREAD

**Issue by AravindaDP** [Azure/connectthedots#171]
Add the ability to implement device operations (methods) which gets executed by downlink messages. This will facilitate automating the systems.

**Comment by AravindaDP** [comment]
I think I probably got it wrong. Looks like Push notifications is the way to go with sending requests back to the devices. And I don't see ability to set push notification as the output of stream analytics jobs output sink. So we may need a service (Can WebJobs be used?) to convert event hub to push notifications?
Or Is there a better way to achieve this

**Comment by olivierbloch** [comment]
Now that we are using IoT Hub instead of Event Hub (since V2) we can do this using native Cloud 2 Device functionality. This is something I am planning to work on soon. Stay tuned.

**Comment by olivierbloch** [comment]
I have added a Cloud to Device message each time an alert is triggered.
