### ISSUE TITLE
What is the Messages section at the bottom?

### ISSUE THREAD

**Issue by ZingPow** [Azure/connectthedots#173]
At the bottom of the web page there is a 'Messages' section, and while the rest of the page seems to getting and displaying data correctly, I'm wondering what the Messages section is an how do I get it to display something other then:
![messagesconnectthedots](https://cloud.githubusercontent.com/assets/9912457/8103614/12bc936a-0fe7-11e5-9a74-ab81422fc1aa.jpg)

Connected.
Connecting to ws://classdemo.azurewebsites.net/api/websocketconnect?clientId=none

**Comment by olivierbloch** [comment]
The messages down there are a place to put traces if needed. The ones showing up here are the websocket connection traces between the browser and the website backend. Closing the issue
