### ISSUE TITLE
GatewayService - sensor data caching

### ISSUE THREAD

**Issue by markhenninger** [Azure/connectthedots#186]
Enhancement request to add local persistent caching of sensor data messages that fail to send to event hub, along with periodic retry.

**Comment by spyrossak** [comment]
Great idea. Even better if you want to contribute solution and issue a pull request! 
Top priorities for us currently are increasing scope around additional devices, cloud services, and analytics, so need your help to develop enhancements such as this. Assigning lower priority for now - may change later.

**Comment by markhenninger** [comment]
I'd like to contribute, just not sure I have the skill and time.  I have deployed the project to evaluate as the basis for an air quality monitoring pilot using low cost sensors.  If we decide to go ahead using connectthedots, I'm sure me or my colleagues will add the enhancement and contribute.  I've actually added some simple features to my installation (SA job to store all data in SQL Server and a web application to view, sort, filter and download).

**Comment by olivierbloch** [comment]
Stale
