### ISSUE TITLE
SensorAgent.py is overused

### ISSUE THREAD

**Issue by lt72** [Azure/connectthedots#193]
calling files with the same not_very_descriptive name is an issue:

Cmd>dir SensorAgent.py /s
 Volume in drive E is Data
 Volume Serial Number is A2BF-6F8C

 Directory of e:\src\iot\connectthedots\Devices\GatewayConnectedDevices\BLEMoisture

07/10/2015  11:24 AM             4,195 SensorAgent.py
               1 File(s)          4,195 bytes

 Directory of e:\src\iot\connectthedots\Devices\GatewayConnectedDevices\Hydrology

07/10/2015  11:24 AM             5,392 SensorAgent.py
               1 File(s)          5,392 bytes

---> e:\src\iot

Calling files with the same not very descriptive name is a problem…

please rename to something more descriptive, and make it different
also please watch for other instances of the same issue

**Comment by olivierbloch** [comment]
Stale
