### ISSUE TITLE
Modify BLEMoisture SensorAgent.py to use config file

### ISSUE THREAD

**Issue by spyrossak** [Azure/connectthedots#194]
Modify SensorAgent.py to read CSV
Move Org, Disp, etc from .py to CSV. Remove hard coding of measure and units from JSON print statement - make it so user neve has to modify Python file.
Add various reserved field names to CSV, analogous to those used for Arduino project, plus MAC address of sensor..
Modify SensorAgent.py to display unknown MAC in display name.
Add flag to send/not send unknown MAC in JSON

**Comment by olivierbloch** [comment]
Stale
