### ISSUE TITLE
AzurePrep and EHConsole failing with LiveID

### ISSUE THREAD

**Issue by spyrossak** [Azure/connectthedots#197]
New issue popping up with AUTH failing with LiveID.

**Comment by spyrossak** [comment]
Seems to work with Outlook.com IDs. Also, steps can be done manually, so seems to be related to authentication function call within AzurePrep and EHConsole. Must be recent change, as these programs handled the auth fine until just now. Investigating further.

**Comment by karlrissland** [comment]
ran into a similar issue using a hotmail account.  Worked using a federated account.  strange thing is that when I tried it again, it said the namespace was already in use, however, I cannot find it in the portal.

**Comment by olivierbloch** [comment]
Stale
