### ISSUE TITLE
Website time axis

### ISSUE THREAD

**Issue by spyrossak** [Azure/connectthedots#198]
User may need to select time scale for data to be displayed on CTD website, as well as starting date.
For example, sensor may send data every 1 minute, in which case current website shows about 10 mins of data; however, user may want to see 1 hour averages over 10 hour period, or 1 day averages over longer period. It would be useful to add feature to website allowing user to select time period and starting date.

**Comment by dinarisio** [comment]
Tested scaling time window changing for online data - js changes only. Started implementing changes for historical data on js and reading from blob on backend.

**Comment by dinarisio** [comment]
Working on js part.

**Comment by olivierbloch** [comment]
Stale
