### ISSUE TITLE
Add support for AllJoyn devices

### ISSUE THREAD

**Issue by spyrossak** [Azure/connectthedots#199]
Current CTD supports any device where you have access to the device or gateway and can modify the output string to send as JSON with the required fields. Would be great to support AllJoyn (See Wikipedia article at https://en.wikipedia.org/wiki/AllJoyn) devices, with the addition of a gateway or bridge - either in CTD or in AllJoyn itself. Should research options.

**Comment by olivierbloch** [comment]
Stale
