### ISSUE TITLE
Website page load times degrade for multiple devices

### ISSUE THREAD

**Issue by spyrossak** [Azure/connectthedots#200]
One user reports that they connected 1,000 virtual spark cores to CTD event hub and observed the following: "Once the page loads, perf is fine, but it seems like perf is 2*n^2 for page load. We tracked this down to the chart resetting all of the chart colors every time a new line is added."

The website example provided in CTD is intended to be an example only, not necessarily scalable to this degree. That being said, would be worth investigating to see if this page load time issue could be addressed.

**Comment by olivierbloch** [comment]
Stale
