### ISSUE TITLE
Problem creating Stream Analytics Aggregates job in UI

### ISSUE THREAD

**Issue by spyrossak** [Azure/connectthedots#202]
Aggregates job uses same event hub for input and output, to allow website to view SA aggregate as just another line to plot. Recent change in ASA portal warns against setting input=output in case of creating loops. Need to investigate whether this stops the job.

**Comment by dinarisio** [comment]
I've created a job and it was working well so far. I think it might be an issue in some cases, but for average with this time window should be ok. Will see if job would stop.

**Comment by spyrossak** [comment]
Did you see the screenshots from HP and the warning message/stoppage they got? Is there something we need to add to the documentation to ignore a warning or something?



Sent from Windows Mail

**Comment by dinarisio** [comment]
Yes, I saw screenshots. I had the same message - it just for aware user I think. If user creates SA jobs via AzurePrep, he would not see this message.

**Comment by spyrossak** [comment]
Thanks.


Sent from Windows Mail

**Comment by olivierbloch** [comment]
Stale
