### ISSUE TITLE
Remove Intel Galileo sample from project

### ISSUE THREAD

**Issue by olivierbloch** [Azure/connectthedots#206]
The Intel Galileo project requires lots of updates and is not used much. I suggest removing it all together and point people to the Raspberry Pi Windows 10 sample for those willing to experience Windows IoT Core.

**Comment by Pooja-B** [comment]
No, please don't do that. Let it be there, it will be useful for many.

**Comment by monteil** [comment]
Hello,
When you say "it requires lots of updates", does it means that the current code is not working properly? 
I have tryied to setup a Galileo Gen 2 board this week following the [instructions] (https://github.com/Azure/connectthedots/blob/master/Devices/DirectlyConnectedDevices/IntelGalileo/Intel-Galileo-setup.md). 
Deployment works fine, but it seems to fail to send an AMQP message. The program looks blocked in the proton lib, when callins pn_messenger_send : No message sent in the Visual Studio output and I do not find any logs file from proton. Any feedback or recommandation would be welcome.If the code no longer works on Galileo, please let us know!
Thanks.

**Comment by ivanignatiev** [comment]
It will be useless code from Novmber 30, 2015. 

> "The support for Windows on Galileo will end on November 30, 2015."
> "Wiring support is now available on Windows 10 IoT Core running on Raspberry Pi 2. This allows you to migrate your existing Galileo projects to Windows 10 IoT Core." - https://ms-iot.github.io/content/en-US/Faqs.htm#galileo
