### ISSUE TITLE
Where can I put the sample for Windows 10 IoT sensor?

### ISSUE THREAD

**Issue by stormy-ua** [Azure/connectthedots#212]
I would like to add a sample showing how HDC1008 temperature & humidity sensor can be integrated with the Connect The Dots. For now, it is residing in my repo. Here is the link to the sample description - https://github.com/stormy-ua/WindowsIoTCore.Drivers/tree/master/Hdc100x/CS/Sample/Azure.EventHub. I have created "driver" for the sensor and have published it to the nuget. Here is the link to the sensor driver - https://github.com/stormy-ua/WindowsIoTCore.Drivers/tree/master/Hdc100x. 

I do not know where it would be better to put this sample. Can you suggest?

**Comment by olivierbloch** [comment]
Hi @stormy-ua , really sorry for not getting back to you earlier on this one.
If you still want to contribute your sample to the project, you can do so creating a folder in https://github.com/Azure/connectthedots/tree/master/Devices/DirectlyConnectedDevices
Note that I will be moving the V1 of the project (using Event Hubs) into a new branch and will push the work in progress branch IoTHub into master. This new version no longer uses Event Hubs, but instead uses IoTHub. So if you still want to contribute your sample using Event Hub to the project, I recommend you do it now or you do it in the V1 branch once I have created it.

**Comment by olivierbloch** [comment]
Stale issue
