### ISSUE TITLE
Consider enabling additional methods of configuration/connection strings in the web app

### ISSUE THREAD

**Issue by jeffwilcox** [Azure/connectthedots#218]
Hi,
Rather than including credentials in `web.config`, I would much rather either use runtime environment configuration variables (for Azure Web Sites hosting) or as a Service Runtime property name (for Cloud Services), this would make it super easy to rotate credentials, etc.

Just opening an issue now, maybe someday I'll get around to submitting a PR :-).

**Comment by olivierbloch** [comment]
Hey @jeffwilcox, I am working on a big update to the whole project (work in progress in the IoTHub branch) that replaces the AzurePrep tool with an ARM template. Settings for the site no longer need to be set in the web.config file manually, the app settings are populated automatically by the ARM template.
If one wants to change the settings at runtime, he can do so in the Azure portal in the Webapp blade.
If that solves the issue, I'll close it when I push the V2!

**Comment by jeffwilcox** [comment]
@olivierbloch sounds great, thanks!

**Comment by olivierbloch** [comment]
@jeffwilcox I have made good progress on the IoTHub port as you can see in the IoTHub branch. I am looking for testers for feedback before merging into master. If you are game... :-)

**Comment by olivierbloch** [comment]
Now that the deployment is done using arm template, there is no longer any need to add the credentials manually in web.config
