### ISSUE TITLE
This is more a question then a issues

### ISSUE THREAD

**Issue by bmorneau** [Azure/connectthedots#219]
Can I use this framework to talk to the sensor, in case the sensor is more then just a temperature reader my can open relay?

**Comment by olivierbloch** [comment]
At this point you cannot do this with these samples which are mainly focused on telemetry data sent from devices up to Azure.
We are working on adding this capability to the samples and you should start seeing some of these in a couple weeks from now.
In the meantime, you can look into options such as Azure Mobile services, Azure Notification Hubs or event Service Bus Topics.
Stay tuned

**Comment by olivierbloch** [comment]
I am making good progress on the Azure IoT Hub support (see the IoTHub branch) which is bringing the ability to send messages back to devices from Azure through Azure IoT Hub. I'll label this issue as a feature request and will close once the V2 is pushed into Master (should be real soon!)

**Comment by olivierbloch** [comment]
IoTHub support is now full there. I have added a Cloud to Device Message from the backend down to the devices each time there is an alert triggered. You can check how it's don't in the latest website code. I will update the devices code as well, for now only the NodeJS desktop sample does something out of the incoming message.
