### ISSUE TITLE
MissingSubscriptionRegistration: The subscription is not registered to use namespace 'Microsoft.StreamAnalytics'

### ISSUE THREAD

**Issue by pietrobr** [Azure/connectthedots#221]
If I run the "AzurePrep" Project I get this error: 

MissingSubscriptionRegistration: The subscription is not registered to use namespace 'Microsoft.StreamAnalytics'. when the output console is "Creating Alert Stream Analytics Jobs..

This happens in both Visual Studio 2013 and Visual Studio 2015. I'm using Azure Tool v 2.7 on MSDN Subscription

**Comment by pietrobr** [comment]
I find out that if I create a test Stream Analytics job from the Azure portal, this operation register the missing namespace (provider?) in the subscription. After that the AzurePrep code works as expected with no errors. Probably the code could be enhanced registering the provider if not already there using REST API.

**Comment by resolutedreamer** [comment]
I am also having this issue. I do not understand how it was solved. How do i "create a test Stream Analytics job from the Azure portal"

**Comment by sudheer594** [comment]
make sure your subscribtion is registered to 'Microsoft.StreamAnalytics'.
In Azure CLI, run "azure provider list" to list all the providers and verify the status.
To register "Microsoft.StreamAnalytics", run "azure provider register Microsoft.StreamAnalytics".

**Comment by rodneyjoyce** [comment]
Update for AZ: az provider register -n Microsoft.StreamAnalytics
