### ISSUE TITLE
No data captured on website deployed

### ISSUE THREAD

**Issue by Muhammad-Fir** [Azure/connectthedots#227]
Hi, I am currently facing some problems regarding the connectthedots proeject. There is currently no data captured on the website that I deployed. I have successfully published the website and enable web sockets. At the bottom of the page, there are 2 statements shown which are 
- Connected.
- Connecting to ws://sensingtemperaturenetwork.azurewebsites.net/api/websocketconnect?clientId=none

Been stuck at this error for days. Would appreciate it if you could help. Thanks.

**Comment by dinarisio** [comment]
Hello @Muhammad-Fir, did you try EHConsole tool to ensure data is coming to the Event Hub?

**Comment by Muhammad-Fir** [comment]
Hello @dinarisio, no I did not as I was following the steps in all the links of the getting started project here - https://github.com/Azure/connectthedots/blob/master/GettingStarted.md
There was no mention of EHConsole. Is it a must to use it? How do I use the tool to ensure that data is coming in?

**Comment by dinarisio** [comment]
https://github.com/Azure/connectthedots/tree/master/Azure/EHConsole. It's just console app that will ask you what EH you are going to use and after couple of minutes starts showing all messages that are coming to EH at the moment.

**Comment by Muhammad-Fir** [comment]
Hello @dinarisio, I generated the Web.config for the website from the 'ConnectTheDots\Azure\WebSite\ConnectTheDotsWebSite\web.config' folder. I have created the stream analytics but when I try to input sample data, there was an error which means that no data is captured.

**Comment by dinarisio** [comment]
Did you change this template by hands? Why not AzurePrep/CreateWebConfig?

What is result of using EHConsole?

**Comment by Muhammad-Fir** [comment]
Hello @dinarisio, I tried the AzurePrep/CreateWebConfig but it still does not work.
As for the EHConsole, I have changed the connection string but the end result is the same.

**Comment by Muhammad-Fir** [comment]
Hello @dinarisio , the EHConsole works. Data is captured from the Arduino and weather shield and can be seen on the event hubs under dashboard but no data is displayed on the website.

**Comment by stevekludt** [comment]
I am having the same issue has Muhammad-Fir.  I have runt he EHConsole app and can see the events.  Also, when I look at the ASA jobs in the azure portal I can see that the events are being processed there, but I am not able to see anything in the website.  The website comes up, but at the bottom I get the same message of:
Connected.
Connecting to ws://datuhcustomerportal.azurewebsites.net/api/websocketconnect?clientId=none

**Comment by Muhammad-Fir** [comment]
Hello @dinarisio, do u know why no data is captured by the weather shield even after I have rebooted the Raspberry Pi many times? A few days ago, data was captured. But today, not even a single data was captured and I have been trying to fixing the problem since the morning.

**Comment by dinarisio** [comment]
@Muhammad-Fir you need to check:
- connection strings are correct
- rc.local is correct so the service is starting
I suggest to set log level to Verbose and see what is happening in gateway logs.

**Comment by Muhammad-Fir** [comment]
@dinarisio How do I set the log level to Verbose?

**Comment by dinarisio** [comment]
@Muhammad-Fir at the end of this file before deploying to Pi. If you want to change on Pi, please change at staging directory as well because this will become the main file on reboot.

**Comment by Muhammad-Fir** [comment]
@dinarisio I have tried everything yet the data seems to come in slowly. There was an instance as well whereby no data was even captured for the entire day and I have no idea what's the root cause of it.

**Comment by dinarisio** [comment]
@Muhammad-Fir  What is the amount of coming data you expect? If you not sure that data is generated with constant interval, you can simulate data stream on Pi say 1 item per second and see what will happen on web site on any changes of your environment.

**Comment by Muhammad-Fir** [comment]
@dinarisio Data is displayed only when I run and open the browser from Visual Studio. If I directly browse it from Azure, no data will be displayed.
Try this as well @stevekludt

**Comment by DanKline** [comment]
This issue is a little old, but when I was experiencing the same problem, it was because I used the connection string for the ehdevices D1 policy, rather than the website policy.

**Comment by olivierbloch** [comment]
Closing this one assuming it's resolved.
