### ISSUE TITLE
MS Band Sensors Flood httpClient

### ISSUE THREAD

**Issue by redraven984** [Azure/connectthedots#230]
Hi All, 

So I have been looking at various exceptions that I am experiencing with this phone app. The main exception I am seeing is "Out of Memory". I have narrowed the problem down to the 'httpClient'. It looks like when I connect too many sensors from the Band 2, the await task is flooded and it causes errors with the client. 

I have tried to change the reporting intervals but it looks like I cant do that on the Band 2. If I request all supported intervals as per the Band SDK, I received only 1 available interval. If I try to set the reporting interval, I get an access violation.

I also tried to create a new httpClient instance for each sensor. This allows the application to run longer but it ultimately still crashes.

So, since I cant change the reporting interval, what can I do with httpClient to make it more robust. It looks like it just cant handle 1 event sent per second.

Thanks!

**Comment by olivierbloch** [comment]
Hi @redaven984 Thanks for the heads up on this one. I was able to get some cycles to work on the project and am almost ready to push the V2 (which is now in the IoTHub branch) into master.
This V2 is no longer using Event Hubs and instead uses IoTHub and the devices are all using the IoTHub SDKs, so this issue will be obsolete.
I am not planning to spend much time on the V1 but I think the workaround would consist in modifying the logic of sending messages no longer when the Band sends an update, but rather within it's own separate thread. This is the way I am doing things in the V2 (you can checkout the UWP Band sample here:  https://github.com/Azure/connectthedots/tree/IoTHub/Devices/DirectlyConnectedDevices/UWPMSBand
