### ISSUE TITLE
Raspberry Pi 3 as a Gateway Device unable to connect IoT Hub

### ISSUE THREAD

**Issue by bunpotth** [Azure/connectthedots#247]
I am building the Connect The Dots Project with Arduino UNO + Sparkfun Weather Shield and using Raspberry Pi as a Gateway by connect Arduino to RPi3 with USB.

I followed the instruction strictly but it still not work.  In RPi3, Gateway service is running but unable to connect to Azure IoT Hub.

I have ensure that IoT Hub is work by using the sample Node.js code to send the message to the IoT Hub.

Could you please help guide on how to diagnose the issue on RPi3?

**Comment by olivierbloch** [comment]
Hi @bunpotth 
Sorry for the late response, I was out on vacation the last 2 weeks :-)
Here are a few things to try and dentify what's going wrong.
Are you building the gateway project in debug or release? try debug if you were using release.
Also, search for the logs subfolder in the gateway app folder on the device to see if you can see any relevant info in there.

**Comment by bunpotth** [comment]
Thank you very for your advice. I will try this on this weekend.

**Comment by olivierbloch** [comment]
hi @bunpotth 
Any success? I'd like to narrow this issue down and any input would be helpful
Thanks

**Comment by olivierbloch** [comment]
Closing because stale. reopen if needed
