### ISSUE TITLE
ESP8266 NodeMCU board, need assistance!

### ISSUE THREAD

**Issue by mdma666** [Azure/connectthedots#253]
do not know how to correct, 

> 
Attempting to connect to SSID: [edge]
scandone
f 0, ....scandone
no [edge] found, reconnect after 1s
reconnect
>

**Comment by olivierbloch** [comment]
Hi @mdma666 
I suppose you are trying to run the C sample for ESP8266...
have you followed the instructions [here](https://github.com/Azure/connectthedots/blob/master/Devices/DirectlyConnectedDevices/ESP8266/ESP8266_setup.md)?
is [edge] the SSID for your wifi router?

**Comment by mdma666** [comment]
[edge] the SSID  my router
I  followed the instructions

**Comment by olivierbloch** [comment]
With the brackets [] ?

**Comment by mdma666** [comment]
no

**Comment by olivierbloch** [comment]
Then you need to try removing the brackets. The code should look like this (replacing "password" with your router password

static char ssid[] = "edge";
static char pass[] = "password";

**Comment by mdma666** [comment]
everything is OK
thanks
