### ISSUE TITLE
nodemcu ans azure event hub 

### ISSUE THREAD

**Issue by rishikeshayre1310** [Azure/connectthedots#254]
hello
Is it possible to use nodemcu to connect the azure event hub. instead of  Azure IoT hub.  i am currently able to connect raspberry pi to azure event hub, i want to move my project from raspberry pi to nodemcu.
can anybody help me with that if it is possible.

**Comment by olivierbloch** [comment]
Hi @rishikeshayre1310 
we are now mostly focused on Azure IoT Hub for the connectthedots project, but let me recommend looking into the Event Hubs SDK: https://github.com/azure/azure-event-hubs.
I have not tested the port on nodemcu myself but I am sure this is doable

**Comment by rishikeshayre1310** [comment]
Thank you @olivierbloch 
I have successfully implemented interfacing Nodemcu with Azure Event Hub.

PS: if anyone is still looking for similar solution please go through this

[](http://stackoverflow.com/questions/40602293/is-it-possible-to-connect-nodemcu-with-microsoft-azure-event-hub)
