### ISSUE TITLE
Enable IoTHub Management - Access still in User Mode

### ISSUE THREAD

**Issue by lazarus-git** [Azure/connectthedots#260]
Hi Olivier
I followed the guide for having the IOTHUB management right, but my user is still in User Mode 
i don't see the Admin mode. The user is Owner of the App and i confirm that i can log in with it.
""""Once you have done so you can go back to the site where you will be prompted to login. Use the same account as your Azure Subscription's one. There you should see a new collumn in the devices list as well as a couple buttons allowing you to create a new device or delete an existing one. No more need to toy around with IoTHub in the portal!"""""""""

Do you know if there is something to create like a group or is there any Admin Mode that we can use ?
regards

**Comment by olivierbloch** [comment]
Hey @lazarus-git 
During deployment of the solution you were given the opportunity to define the (one) email to be used as admin.
If you have deployed and forgot to fill in the email address there, then you can do this post-deployment going to the azure portal, in the WebApp blade for your CTD solution, and look for "Application Settings" blade. Once you brought the app settings blade up, scroll down to find the parameter "AdminName" and make sure the value is the email address you want to be the admin for your site.
Let me know if that works for you

**Comment by olivierbloch** [comment]
Hi @lazarus-git 
did that solve your issue?
Thanks
