### ISSUE TITLE
Deployment Fails

### ISSUE THREAD

**Issue by kentstroker** [Azure/connectthedots#266]
Deployment fails with an object not defined error when using the deploy button method.

So I tried using the command line method for deploying works.

**Comment by olivierbloch** [comment]
Hi @kentstroker 
I did a minor edit to the readme which was using an https link for the deploy button service which seems to not have SSL anymore. I switched to http and was able to deploy using the button.
If you have some time, do you mind verifying it works for you as well? And if not, can you share some more details?
Thanks

**Comment by olivierbloch** [comment]
I will close the issue assuming everything is now fine. Feel free to submit a new one if that's not the case. thanks
