### ISSUE TITLE
Issue with gateway service

### ISSUE THREAD

**Issue by dvescovi1** [Azure/connectthedots#269]
Hello Olivier:
I was able to successfully clone and build the connetthedots project in VS2017.
I have my resources provisioned on Azure and I am able to modify and deploy the web site just fine.
I have been trying to run the ConnectTheDots.GatewayExe but I keep getting the following error:

2017-08-27 16:59:00.1705 ERROR System.ServiceModel.AddressAccessDeniedException: HTTP could not register URL http://+:8000/GatewayService/. Your process does not have access rights to this namespace (see http://go.microsoft.com/fwlink/?LinkId=70353 for details). ---> System.Net.HttpListenerException: Access is denied

I have configured the IoT Hub connection string in the App.config. 
I am not sure but I think I must also change the baseAddress to point to my azure web site??

I tried to change this to:

   add baseAddress="http://dvmyctd.azurewebsites.net:8000/GatewayService/" 
 
But I still get this error
Any suggestions?

David Vescovi

**Comment by dinarisio** [comment]
Hi David,

Discussions in stackoverflow are suggesting to run app with admin privileges.

Where the gateway service is hosted? I believe it should be your local device in typical deployments, not we Azure Website - it is used to push data from local network to Azure.

-Dinar

**Comment by olivierbloch** [comment]
Hey @dvescovi1 , let us know if you were able to solve your issue following Dinar's suggestion

**Comment by dvescovi1** [comment]
Running VS in admin mode, changing BaseAddress back to LocalHost and moving port to 8006 instead of 8000 seems to have fixed the issue. Apparently I already have something else running on 8000 ;)
