### ISSUE TITLE
Deployment error using the ARM template

### ISSUE THREAD

**Issue by akobyl** [Azure/connectthedots#272]
When clicking the button for Deploy to Azure I get a Deployment error:

> Submitting Deployment
> Deployment Started
> Updating Microsoft.Devices/Iothubs
> Updating Microsoft.Storage/storageAccounts
> Updating Microsoft.Eventhub/namespaces
> Creating Web Hosting Plan
> Updating Microsoft.Eventhub/namespaces/authorizationRules
> Updating Microsoft.Eventhub/namespaces/eventHubs 
> Deployment Failed (View Error)
 
and the error..

> No registered resource provider found for location 'westus' and API version '2018-01-01-preview' for type 'namespaces/authorizationrules'. The supported api-versions are '2014-09-01, 2015-08-01, 2017-04-01'. The supported locations are ''.

My setup page is with:

- Free Trial account
- Create new Resource Group
- Default Resource group name `connectthedots07f2`
- Region West US (East US also failed)
- solution name `metrics`
- Iot Hub Sku `F1`
- Admin name (my Azure account email)

**Comment by akobyl** [comment]
Deploying via the CLI produces a little more detail:

> Deployment failed. Correlation ID: a6102976-4f55-4b84-b5d8-07452c342cb0. {
  "error": {
    "code": "NoRegisteredProviderFound",
    "message": "No registered resource provider found for location 'eastus' and API version '2018-01-01-preview' for type 'namespaces/authorizationrules'. The supported api-versions are '2014-09-01, 2015-08-01, 2017-04-01'. The supported locations are ''."
  }
}

**Comment by wagsousa** [comment]
#273

**Comment by olivierbloch** [comment]
Thanks for the PR. I merged it in, but then decided to opt for hard coding specific version of the API. I also fixed the master Readme to point to the right template (for some reason it was pointing to one sitting in a different branch).
