### ISSUE TITLE
Add TI BT sensor to project

### ISSUE THREAD

**Issue by spyrossak** [Azure/connectthedots#72]
Has dependency on BT interface on gateway being enabled

**Comment by ppatierno** [comment]
Hi,
are you speaking about TI Sensor Tag ? If yes, I'm developing a demo for the "Internet of Things Conference" in Naples on April 18th. In the demo I have a FEZ Spider board (.Net Gadgeteer) with a BLE module that acquires data from TI Sensor Tag and sends them to the Event Hubs.
I'll put it online and I think that it could be useful to this issue.

Paolo.

**Comment by olivierbloch** [comment]
Stale. Closing
